/** Dory mail gateway. Deploy as ricimarino@gmail.com, execute as me. */
function doPost(e) {
  var lock = LockService.getScriptLock(); lock.waitLock(20000);
  try {
    var data=JSON.parse(e.postData.contents||'{}'),properties=PropertiesService.getScriptProperties(),secret=properties.getProperty('DORY_CONFIRMATION_TOKEN');
    if(!secret||data.token!==secret)return reply_({ok:false,error:'unauthorized'});
    if(Session.getEffectiveUser().getEmail().toLowerCase()!=='ricimarino@gmail.com')return reply_({ok:false,error:'wrong-owner'});
    var type=String(data.type||'confirmation'),emailRequired=type!=='cancellation'&&type!=='manager-confirmation';
    if(!/^[0-9a-f-]{36}$/i.test(String(data.id||''))||(emailRequired&&!/^\S+@\S+\.\S+$/.test(String(data.email||'')))||!data.name||!data.offer||!(Number(data.people)>0))return reply_({ok:false,error:'invalid-booking'});
    var id=String(data.id),email=String(data.email||'').toLowerCase(),people=Number(data.people),peopleText=people+(people===1?' persona':' persone');
    if(type==='cancellation'){
      var managerKey='cancelled-managers:'+id,guestKey='cancelled-guest:'+id;
      if(!properties.getProperty(managerKey)){sendDoryMail_({to:'ricimarino@gmail.com,giuseppeucci8@gmail.com',subject:'Dory · Prenotazione cancellata: '+data.name,eyebrow:'GESTIONE EQUIPAGGIO',title:'Prenotazione cancellata',intro:'Ric e Peppe, la prenotazione è stata cancellata dalla Gestione equipaggio.',rows:[['Nome',data.name],['Uscita',data.offer],['Persone',peopleText],['Email ospite',email||'non indicata']],notice:'Il posto è di nuovo disponibile. Calendar verrà aggiornato dalla sincronizzazione.',noticeTone:'orange'});properties.setProperty(managerKey,new Date().toISOString());}
      if(email&&!properties.getProperty(guestKey)){sendDoryMail_({to:email,subject:'Dory · La tua prenotazione è stata cancellata',eyebrow:'DORY',title:'Cambio di rotta',intro:'Ciao '+data.name+', Ric e Peppe hanno cancellato la tua prenotazione.',rows:[['Uscita',data.offer],['Persone',peopleText]],paragraphs:['L’invito verrà rimosso dal calendario. Se vuoi protestare, fuori bordo puoi perfino insultare i Comandanti: a bordo la loro parola è legge, qui puoi sbizzarrirti rispondendo alla mail.'],notice:'Cancellazione registrata',noticeTone:'orange',signoff:'Ric e Peppe'});properties.setProperty(guestKey,new Date().toISOString());}
      return reply_({ok:true});
    }
    if(type==='manager-confirmation'){
      var confirmedKey='confirmed-managers:'+id;if(properties.getProperty(confirmedKey))return reply_({ok:true,alreadySent:true});
      var who=data.addedBy==='peppe'?'Peppe':data.addedBy==='ric'?'Ric':'Gestione equipaggio';
      sendDoryMail_({to:'ricimarino@gmail.com,giuseppeucci8@gmail.com',subject:'Dory · Equipaggio confermato: '+data.name,eyebrow:'GESTIONE EQUIPAGGIO',title:'Posto confermato',intro:who+' ha aggiunto e confermato una prenotazione dalla Gestione equipaggio.',rows:[['Nome',data.name],['Uscita',data.offer],['Persone',peopleText],['Email ospite',email||'non indicata']],notice:'Conferma registrata. Calendar verrà aggiornato dalla sincronizzazione.',noticeTone:'green'});properties.setProperty(confirmedKey,new Date().toISOString());return reply_({ok:true});
    }
    if(type==='new-request'){
      var noticeKey='notified:'+id;if(properties.getProperty(noticeKey))return reply_({ok:true,alreadySent:true});
      sendDoryMail_({to:'ricimarino@gmail.com,giuseppeucci8@gmail.com',subject:'Dory · Nuova richiesta di imbarco: '+data.name,eyebrow:'NUOVA RICHIESTA',title:'Qualcuno vuole salire a bordo',intro:'È arrivata una nuova richiesta di imbarco su Dory.',rows:[['Nome',data.name],['Uscita',data.offer],['Persone',peopleText],['Email',email],['Note',data.message||'Nessuna']],notice:'Richiesta da confermare nella Gestione equipaggio.',noticeTone:'orange'});properties.setProperty(noticeKey,new Date().toISOString());return reply_({ok:true});
    }
    if(type!=='confirmation')return reply_({ok:false,error:'invalid-type'});
    var key='sent:'+id+':'+email;if(properties.getProperty(key))return reply_({ok:true,alreadySent:true});
    sendDoryMail_({to:email,subject:'Dory · Sei dei nostri ⛵',eyebrow:'UN POSTO PER TE A BORDO',title:'Ci siamo: posto confermato a bordo di Dory! ⛵',intro:'Ciao '+data.name+', ora viene la parte in cui fingiamo di avere tutto sotto controllo.',rows:[['Uscita',data.offer],['Equipaggio',peopleText]],paragraphs:['Il meteo comanda, Ric e Peppe fingono di farlo. Nei 3 giorni prima dell’uscita controlliamo vento, mare e previsioni e decidiamo se si salpa. Orario, punto d’imbarco ed eventuali cambi di programma arrivano direttamente dai Comandanti.','Per salire a bordo servono due cose poco romantiche ma necessarie: tessera sportiva AICS (10 €) e certificato medico non agonistico.','Per Dory, se ti va, un contributo volontario al fondo cassa è sempre benvenuto: serve per prenderci cura della barca. Perché, inspiegabilmente, anche le barche mangiano soldi.','Per tutto il resto ci sentiamo prima dell’uscita. Tu intanto porta la voglia di mare. Al resto pensiamo noi.'],notice:'Posto confermato · mare permettendo!',noticeTone:'green',signoff:'A presto a bordo!<br>Ric e Peppe'});properties.setProperty(key,new Date().toISOString());return reply_({ok:true});
  }catch(err){return reply_({ok:false,error:String(err)});}finally{lock.releaseLock();}
}
function sendDoryMail_(o){var plain=(o.title||'Dory')+'\n\n'+(o.intro||'')+'\n\n';(o.rows||[]).forEach(function(r){plain+=r[0]+': '+r[1]+'\n';});(o.paragraphs||[]).forEach(function(p){plain+='\n'+p+'\n';});if(o.notice)plain+='\n'+o.notice+'\n';if(o.signoff)plain+='\n'+String(o.signoff).replace(/<br\s*\/?\s*>/gi,'\n')+'\n';MailApp.sendEmail({to:o.to,subject:o.subject,body:plain,htmlBody:doryEmailHtml_(o),name:'Ric e Peppe'});}
function doryEmailHtml_(o){
  var esc=function(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');};
  var rows=(o.rows||[]).map(function(r){return '<tr><td style="padding:7px 12px 7px 0;font-family:Arial,sans-serif;font-size:12px;line-height:18px;color:#718487;text-transform:uppercase;vertical-align:top;white-space:nowrap;">'+esc(r[0])+'</td><td style="padding:7px 0;font-family:Arial,sans-serif;font-size:15px;line-height:21px;font-weight:700;color:#15363c;vertical-align:top;word-break:break-word;">'+esc(r[1])+'</td></tr>';}).join('');
  var paragraphs=(o.paragraphs||[]).map(function(p){return '<p style="margin:0 0 13px;font-family:Arial,sans-serif;font-size:15px;line-height:22px;color:#29484d;">'+esc(p)+'</p>';}).join('');
  var tone=o.noticeTone==='orange'?'#fff1df':'#e8f5ef',border=o.noticeTone==='orange'?'#ef9b52':'#86c5ad',ink=o.noticeTone==='orange'?'#70410f':'#174c3a';
  var notice=o.notice?'<table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td style="padding:12px 14px;background-color:'+tone+';border:2px solid '+border+';font-family:Arial,sans-serif;font-size:14px;line-height:20px;font-weight:700;color:'+ink+';">'+esc(o.notice)+'</td></tr></table>':'';
  var signoff=o.signoff?'<p style="margin:16px 0 0;font-family:Arial,sans-serif;font-size:15px;line-height:22px;font-weight:700;color:#15363c;">'+String(o.signoff)+'</p>':'';
  return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background-color:#f4f7f6;"><table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:#f4f7f6;"><tr><td align="center" style="padding:16px 10px;"><table role="presentation" width="560" border="0" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;background-color:#ffffff;border:1px solid #d9e7e4;"><tr><td style="padding:22px 22px 8px;font-family:Arial,sans-serif;font-size:11px;line-height:16px;font-weight:700;letter-spacing:1px;color:#e88936;">'+esc(o.eyebrow||'DORY')+'</td></tr><tr><td style="padding:0 22px 10px;font-family:Arial,sans-serif;font-size:22px;line-height:27px;font-weight:700;color:#15363c;">'+esc(o.title||'Dory')+'</td></tr><tr><td style="padding:0 22px 14px;font-family:Arial,sans-serif;font-size:15px;line-height:22px;color:#29484d;">'+esc(o.intro||'')+'</td></tr>'+(rows?'<tr><td style="padding:0 22px 15px;"><table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top:1px solid #e5eeec;border-bottom:1px solid #e5eeec;">'+rows+'</table></td></tr>':'')+'<tr><td style="padding:0 22px 22px;">'+paragraphs+notice+signoff+'</td></tr></table><table role="presentation" width="560" border="0" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;"><tr><td align="center" style="padding:8px 0 0;font-family:Arial,sans-serif;font-size:11px;line-height:16px;color:#809296;">Dory · Ric e Peppe</td></tr></table></td></tr></table></body></html>';
}
function reply_(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
