"use client";
import {useEffect,useState} from "react";
import {offers as seed,weeks,type Offer} from "@/lib/plan";
import "./dory.css";
type Live=Offer&{capacity:number;confirmed:number;available:number;note:string};
type Booking={id:string;slot_id:string;name:string;email:string;people:number;message:string;status:string;added_by:string;created_at:string};
type ApiData={offers:Live[];requests:Booking[];error:string;message:string};
export default function Home(){
 const [offers,setOffers]=useState<Live[]>(seed.map(x=>({...x,capacity:x.defaultCapacity,confirmed:0,available:x.defaultCapacity,note:""})));
 const [selected,setSelected]=useState<Live|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[loginBusy,setLoginBusy]=useState(false),[adminName,setAdminName]=useState(""),[bookings,setBookings]=useState<Booking[]>([]),[error,setError]=useState(""),[editing,setEditing]=useState<string|null>(null),[showCancelled,setShowCancelled]=useState(false);
 async function refresh(){try{let r=await fetch("/api/overview",{cache:"no-store"});if(!r.ok)throw Error();setOffers(((await r.json()) as ApiData).offers)}catch{setError("Disponibilità temporaneamente non aggiornata.")}}
 useEffect(()=>{refresh();fetch("/api/session",{cache:"no-store"}).then(r=>r.json()).then((j:{manager?:string})=>{if(j.manager)setAdminName(j.manager==="peppe"?"Peppe":"Ric")}).catch(()=>{})},[]);
 useEffect(()=>{
   const context=(document as Document&{modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
   if(!context?.registerTool)return;
   const lifecycle=new AbortController();
   void Promise.resolve(context.registerTool({name:"request_dory_berth",title:"Richiedi un posto su Dory",description:"Invia una richiesta di imbarco in attesa della conferma di Riccardo e Peppe.",inputSchema:{type:"object",properties:{slotId:{type:"string"},name:{type:"string"},email:{type:"string"},people:{type:"integer"},message:{type:"string"}},required:["slotId","name","email","people"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const r=await fetch("/api/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const j=(await r.json()) as ApiData;if(!r.ok)throw Error(j.error);await refresh();setNotice("Richiesta registrata: Riccardo e Peppe la valuteranno.");return {status:"pending",message:j.message}}},{signal:lifecycle.signal})).catch(()=>{});
   return()=>lifecycle.abort();
 },[]);
 async function openAdmin(){if(admin){setAdmin(false);return}let r=await fetch("/api/requests",{cache:"no-store"});if(r.ok){setBookings(((await r.json()) as ApiData).requests);setAdmin(true);setLogin(false);setError("")}else setLogin(true)}
 async function signIn(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoginBusy(true);setError("");const form=e.currentTarget;let d=new FormData(form);try{let r=await fetch("/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:d.get("code")})});let j=await r.json() as {manager?:string;error?:string};if(!r.ok)throw Error(j.error??"Riprova tra poco");setAdminName(j.manager==="peppe"?"Peppe":"Ric");form.reset();setLogin(false);await openAdmin()}catch(e){setError(e instanceof Error?e.message:"Riprova tra poco")}finally{setLoginBusy(false)}}
 async function signOut(){await fetch("/api/session",{method:"DELETE"});setAdmin(false);setAdminName("");setBookings([]);setNotice("Gestione chiusa.")}
 async function manage(body:object){try{let r=await fetch("/api/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});let j=(await r.json()) as ApiData;if(!r.ok)throw Error(j.error);setError("");await refresh();let q=await fetch("/api/requests",{cache:"no-store"});if(q.ok)setBookings(((await q.json()) as ApiData).requests);return true}catch(e){setError(e instanceof Error?e.message:"Modifica non riuscita");return false}}
 async function cancelBooking(b:Booking){if(!window.confirm(`Cancellare ${b.name} da ${offers.find(x=>x.id===b.slot_id)?.title??"Dory"}? Il posto tornerà disponibile.`))return;const ok=await manage({action:"cancel",id:b.id});if(ok){setEditing(null);setNotice(`${b.name} cancellato. Il posto è di nuovo disponibile.`)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);let d=new FormData(e.currentTarget);try{let r=await fetch("/api/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slotId:selected.id,name:d.get("name"),email:d.get("email"),people:Number(d.get("people")),message:d.get("message")})});let j=(await r.json()) as ApiData;if(!r.ok)throw Error(j.error);setSelected(null);setNotice("Richiesta registrata: Riccardo e Peppe la valuteranno.");await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Riprova tra poco")}finally{setBusy(false)}}
 return <main className="shell"><header className="top"><div className="brand"><span className="mark">D</span>Dory</div><div className="topactions">{adminName&&<button className="link" onClick={signOut}>Esci, {adminName}</button>}<button className="link" onClick={openAdmin}>{admin?"Torna alle uscite":"Gestione equipaggio"}</button></div></header>
 <section className="hero"><div><span className="eyebrow">Calendario 2026–2027</span><h1>Le prossime uscite<br/>di Dory</h1><p>Scegli un’uscita o una tratta e chiedi di salire a bordo con Riccardo e Peppe. Ti confermeremo l’imbarco dopo aver composto l’equipaggio. La rotta la decide prima di tutto il mare.</p></div><aside><span className="eyebrow">A bordo sempre</span><strong>Riccardo<br/>e Peppe</strong><p>Fino a 6 posti per gli ospiti per ciascuna proposta, riducibili da noi. Il massimo ordinario è 8 persone in tutto.</p></aside></section>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {admin?<section className="admin"><h2>Posti e richieste</h2><p>Ric e Peppe sono già conteggiati. Le richieste in attesa non occupano posti. Per ora le modifiche al Calendar richiedono un allineamento separato.</p>
 <div className="addcrew"><h3>Aggiungi qualcuno all’equipaggio</h3><p>Il posto viene confermato subito. Il sistema registra automaticamente se l’hai aggiunto tu o Peppe.</p>
 <form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;let d=new FormData(form);void manage({action:"add",slotId:d.get("slotId"),name:d.get("name"),email:d.get("email"),people:Number(d.get("people")),message:d.get("message")}).then(ok=>{if(ok)form.reset()})}}>
 <label>Uscita o tratta<select name="slotId" required>{offers.filter(x=>x.kind!=="party").map(x=><option key={x.id} value={x.id}>{x.dates} · {x.title}</option>)}</select></label>
 <label>Nome e cognome<input name="name" required minLength={2} maxLength={100}/></label><label>Email per l’invito<input name="email" type="email" placeholder="Se disponibile"/></label><label>Persone<input name="people" type="number" min="1" max="6" defaultValue="1" required/></label>
 <label>Nota facoltativa<input name="message" maxLength={500}/></label><button className="primary">Aggiungi</button></form></div>
 {offers.filter(x=>x.kind!=="party").map(x=><div className="adminrow" key={x.id}><strong>{x.dates} · {x.title}</strong><p>{x.confirmed} confermati · {x.available} disponibili</p><form onSubmit={e=>{e.preventDefault();let d=new FormData(e.currentTarget);manage({action:"capacity",slotId:x.id,capacity:Number(d.get("capacity")),note:d.get("note")})}}><label>Posti ospiti <input aria-label={`Posti per ${x.title}`} key={`${x.id}-${x.capacity}`} name="capacity" type="number" min="0" max="6" defaultValue={x.capacity}/></label><label>Nota <input aria-label={`Nota per ${x.title}`} key={`${x.id}-${x.note}`} name="note" defaultValue={x.note}/></label><button>Salva</button></form></div>)}
 <div className="report-head"><div><h2>Report equipaggio</h2><p>{bookings.filter(b=>b.status==="confirmed").length} confermati · {bookings.filter(b=>b.status==="pending").length} in attesa · {bookings.filter(b=>b.status==="declined").length} non accolti</p></div><label><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/> Mostra cancellati ({bookings.filter(b=>b.status==="cancelled").length})</label></div>
 {bookings.length===0&&<p>Non ci sono ancora richieste o inserimenti.</p>}
 {offers.filter(x=>bookings.some(b=>b.slot_id===x.id&&(showCancelled||b.status!=="cancelled"))).map(x=><div className="report-group" key={x.id}><h3>{x.dates} · {x.title}</h3><p>{x.confirmed} persone confermate · {x.available} posti disponibili</p>{bookings.filter(b=>b.slot_id===x.id&&(showCancelled||b.status!=="cancelled")).map(b=><article className="booking" key={b.id}><div className="booking-title"><strong>{b.name}</strong><span className={`status ${b.status}`}>{b.status==="confirmed"?"Confermato":b.status==="pending"?"In attesa":b.status==="declined"?"Non accolto":"Cancellato"}</span></div><p>{b.people} {b.people===1?"persona":"persone"} · {b.added_by==="ric"?"Aggiunto da Ric":b.added_by==="peppe"?"Aggiunto da Peppe":"Richiesta dell’ospite"} · Inserito il {new Date(b.created_at).toLocaleDateString("it-IT")}</p><p>{b.email?`Email: ${b.email}`:"Email non indicata: invito impossibile finché non viene aggiunta"}</p>{b.message&&<p>Note: {b.message}</p>}{b.status!=="cancelled"&&<><div className="actions"><button onClick={()=>setEditing(editing===b.id?null:b.id)}>{editing===b.id?"Chiudi modifica":"Modifica dettagli"}</button>{b.status!=="confirmed"&&<button onClick={()=>manage({action:"status",id:b.id,status:"confirmed"})}>Conferma</button>}{b.status!=="pending"&&<button onClick={()=>manage({action:"status",id:b.id,status:"pending"})}>In attesa</button>}{b.status!=="declined"&&<button onClick={()=>manage({action:"status",id:b.id,status:"declined"})}>Non accogliere</button>}<button className="danger" onClick={()=>cancelBooking(b)}>Cancella</button></div>{editing===b.id&&<form className="editbooking" onSubmit={e=>{e.preventDefault();let d=new FormData(e.currentTarget);void manage({action:"edit",id:b.id,name:d.get("name"),email:d.get("email"),people:Number(d.get("people")),message:d.get("message")}).then(ok=>{if(ok)setEditing(null)})}}><label>Nome e cognome<input name="name" defaultValue={b.name} required minLength={2} maxLength={100}/></label><label>Email<input name="email" type="email" defaultValue={b.email}/></label><label>Persone<input name="people" type="number" min="1" max="6" defaultValue={b.people} required/></label><label>Note<textarea name="message" maxLength={500} defaultValue={b.message}/></label><button className="primary">Salva modifiche</button></form>}</>}</article>)}</div>)}
 </section>:<>
 <section className="rules"><h2>Prima di salire a bordo</h2><p className="requirement"><strong>Il trick: le giornate didattiche.</strong> Per partecipare serve la tessera sportiva AICS (10 € per il tesseramento) e un certificato medico non agonistico. Ti daremo le indicazioni per sistemare tutto prima dell’imbarco.</p><ul><li>Il meteo decide partenze, navigazione, rotta, rada e rientro. I dettagli si confermano vicino alla data.</li><li>Per giornate e pernotti, se ti va, puoi lasciare un contributo libero per la cura di Dory.</li><li>Per la notte la prima scelta è la rada. Se serve un porto, divideremo la spesa tra tutti, Ric e Peppe compresi. Anche la cambusa si sceglie e si divide insieme.</li><li>Per gli imbarchi fuori Ostia cercheremo scali e orari comodi. Il viaggio per raggiungerci o tornare a casa lo organizza ciascuno.</li><li>Se il meteo ci regala il tramonto, aperitivo a bordo!</li></ul></section>
 {weeks.map((week,i)=><section key={week}><h2 className="week"><small>Settimana {i+1} di 6</small><br/>{week}</h2><div className="grid">{offers.filter(x=>x.week===week).map(x=><article className="card" key={x.id}><span className="tag">{x.dates}</span><h3>{x.title}</h3><p>{x.detail}</p><p className="muted">{x.hint}</p>{x.note&&<p className="notice">{x.note}</p>}<footer><span>{x.kind==="party"?"Adesioni aperte":x.capacity===0?"Posti ancora chiusi":`${x.available} posti disponibili`}</span><button disabled={x.capacity===0||x.available===0} onClick={()=>{setSelected(x);setNotice("")}}>Chiedi di salire</button></footer></article>)}</div></section>)}
 </>}
 {login&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setLogin(false)}}><div className="modal login" role="dialog" aria-modal="true" aria-label="Accesso gestione equipaggio"><button className="close" onClick={()=>{setLogin(false);setError("")}}>Chiudi</button><span className="eyebrow">Solo per Ric e Peppe</span><h2>Benvenuto a bordo.</h2><p>Per gestire equipaggio, conferme e posti usa il tuo codice personale. Non serve un account ChatGPT.</p>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={signIn}><label>Codice personale<input name="code" type="password" autoComplete="current-password" required autoFocus/></label><button className="primary" disabled={loginBusy}>{loginBusy?"Verifica…":"Entra nella gestione"}</button></form></div></div>}
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="modal" role="dialog" aria-modal="true" aria-label="Richiesta di imbarco"><button className="close" onClick={()=>setSelected(null)}>Chiudi</button><h2>Chiedi di salire</h2><p><strong>{selected.title}</strong><br/>{selected.dates}</p><p>La richiesta resta in attesa fino alla conferma di Riccardo e Peppe.</p>{selected.kind!=="party"&&<p className="requirement"><strong>Per salire a bordo:</strong> tessera sportiva AICS (10 €) e certificato medico non agonistico. Ti spiegheremo come fare prima dell’uscita.</p>}<form onSubmit={submit}><label>Nome e cognome<input name="name" minLength={2} maxLength={100} required autoComplete="name"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Numero di persone<input name="people" type="number" min="1" max={selected.kind==="party"?20:Math.min(6,selected.available)} defaultValue="1" required/></label><label>Note o giorni preferiti<textarea name="message" maxLength={500}/></label><button className="primary" disabled={busy}>{busy?"Invio…":"Invia richiesta"}</button></form></div></div>}
 </main>
}
