"use client";
import {useEffect,useRef,useState} from "react";
import {offers as seed,weeks,type Offer} from "@/lib/plan";
import "./dory.css";
type Live=Offer&{capacity:number;confirmed:number;available:number;note:string};
type Booking={id:string;slot_id:string;name:string;email:string;people:number;message:string;status:string;added_by:string;created_at:string;confirmation_sent_at:string|null;confirmation_sent_to:string|null;cancellation_sent_at:string|null};
type ApiData={offers:Live[];requests:Booking[];error:string;message:string;confirmation?:{sent:boolean;error?:string}|null;cancellation?:{sent:boolean;error?:string}|null};
const dateRules:Record<string,{min:string;max:string;label:string}>={"feb-day":{min:"2027-02-15",max:"2027-02-21",label:"Scegli il giorno tra il 15 e il 21 febbraio"},"sep-day":{min:"2027-09-20",max:"2027-09-23",label:"Scegli il giorno tra il 20 e il 23 settembre"}};
const packMessage=(date:FormDataEntryValue|null,message:FormDataEntryValue|null)=>`${date?`[DORY-DATE:${String(date)}]\n`:""}${String(message??"").trim()}`.trim();
const unpackMessage=(message:string)=>({date:message.match(/^\[DORY-DATE:(\d{4}-\d{2}-\d{2})\]/)?.[1]??"",note:message.replace(/^\[DORY-DATE:\d{4}-\d{2}-\d{2}\]\s*/,"")});
const prettyDate=(date:string)=>date?new Date(date+"T12:00:00").toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"";
export default function Home(){
 const [offers,setOffers]=useState<Live[]>(seed.map(x=>({...x,capacity:x.defaultCapacity,confirmed:0,available:x.defaultCapacity,note:""}))),[selected,setSelected]=useState<Live|null>(null),[notice,setNotice]=useState(""),[actionNotice,setActionNotice]=useState(""),[submitError,setSubmitError]=useState(""),[submitted,setSubmitted]=useState(false),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[loginBusy,setLoginBusy]=useState(false),[adminName,setAdminName]=useState(""),[bookings,setBookings]=useState<Booking[]>([]),[error,setError]=useState(""),[editing,setEditing]=useState<string|null>(null),[showCancelled,setShowCancelled]=useState(false),[openReport,setOpenReport]=useState<string|null>(null),[adminSlot,setAdminSlot]=useState(seed.find(x=>x.kind!=="party")?.id??"");
 const requestId=useRef<string|null>(null),requestSlotId=useRef<string|null>(null);
 async function refresh(){try{const r=await fetch("/api/overview",{cache:"no-store"});if(!r.ok)throw Error();setOffers(((await r.json()) as ApiData).offers)}catch{setError("Disponibilità temporaneamente non aggiornata.")}}
 async function refreshBookings(){const q=await fetch("/api/requests",{cache:"no-store"});if(q.ok)setBookings(((await q.json()) as ApiData).requests)}
 useEffect(()=>{void refresh();fetch("/api/session",{cache:"no-store"}).then(r=>r.json() as Promise<{manager?:string}>).then(j=>{if(j.manager)setAdminName(j.manager==="peppe"?"Peppe":"Ric")}).catch(()=>{})},[]);
 async function openAdmin(){if(admin){setAdmin(false);return}const r=await fetch("/api/requests",{cache:"no-store"});if(r.ok){setBookings(((await r.json()) as ApiData).requests);setAdmin(true);setLogin(false);setError("")}else setLogin(true)}
 async function signIn(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoginBusy(true);setError("");const f=e.currentTarget,d=new FormData(f);try{const r=await fetch("/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:d.get("code")})});const j=await r.json() as {manager?:string;error?:string};if(!r.ok)throw Error(j.error??"Riprova tra poco");setAdminName(j.manager==="peppe"?"Peppe":"Ric");f.reset();setLogin(false);await openAdmin()}catch(e){setError(e instanceof Error?e.message:"Riprova tra poco")}finally{setLoginBusy(false)}}
 async function signOut(){await fetch("/api/session",{method:"DELETE"});setAdmin(false);setAdminName("");setBookings([]);setNotice("Gestione chiusa.")}
 async function manage(body:object){setActionNotice("");try{const r=await fetch("/api/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=(await r.json()) as ApiData;if(!r.ok)throw Error(j.error);setError("");if(j.confirmation)setActionNotice(j.confirmation.sent?"✓ Email di conferma inviata.":j.confirmation.error??"Email non inviata.");if(j.cancellation)setActionNotice(j.cancellation.sent?"✓ Cancellazione registrata e notifiche inviate. Calendar si aggiorna periodicamente.":`Cancellazione registrata, ma ${j.cancellation.error??"la notifica non è partita"}`);await refresh();await refreshBookings();return true}catch(e){setError(e instanceof Error?e.message:"Modifica non riuscita");return false}}
 async function cancelBooking(b:Booking){if(!window.confirm(`Cancellare ${b.name}? Il posto torna disponibile e partiranno le notifiche.`))return;const ok=await manage({action:"cancel",id:b.id});if(ok)setEditing(null)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||busy)return;setBusy(true);setSubmitError("");const d=new FormData(e.currentTarget),rule=dateRules[selected.id];if(rule&&!d.get("chosenDate")){setSubmitError("Scegli la data dell’uscita.");setBusy(false);return}if(requestSlotId.current!==selected.id){requestId.current=null;requestSlotId.current=selected.id}requestId.current??=crypto.randomUUID();try{const r=await fetch("/api/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId:requestId.current,slotId:selected.id,name:d.get("name"),email:d.get("email"),people:Number(d.get("people")),message:packMessage(d.get("chosenDate"),d.get("message"))}),signal:AbortSignal.timeout(30000)}),j=(await r.json()) as ApiData;if(!r.ok)throw Error(j.error);setSubmitted(true);requestId.current=null;requestSlotId.current=null;void refresh()}catch(e){setSubmitError(e instanceof Error&&e.name==="TimeoutError"?"La risposta sta tardando. Puoi riprovare senza creare doppioni.":e instanceof Error?e.message:"Riprova tra poco")}finally{setBusy(false)}}
 const adminRule=dateRules[adminSlot];
 return <main className="shell"><header className="top"><div className="brand"><span className="mark">D</span>Dory</div><div className="topactions">{adminName&&<button className="link" onClick={signOut}>Esci, {adminName}</button>}<button className="link" onClick={openAdmin}>{admin?"Torna alle uscite":"Gestione equipaggio"}</button></div></header>
 <section className="hero"><div><span className="eyebrow">Calendario 2026–2027</span><h1>Le prossime uscite<br/>di Dory</h1><p>Scegli un’uscita o una tratta e chiedi di salire a bordo con Riccardo e Peppe. Ti confermeremo l’imbarco dopo aver composto l’equipaggio. La rotta la decide prima di tutto il mare.</p></div><aside><span className="eyebrow">A bordo sempre</span><strong>Riccardo<br/>e Peppe</strong><p>Fino a 6 posti per gli ospiti per ciascuna proposta, riducibili da noi. Il massimo ordinario è 8 persone in tutto.</p></aside></section>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{actionNotice&&<p className="action-notice" role="status">{actionNotice}</p>}
 {admin?<section className="admin"><h2>Posti e richieste</h2><p>Ric e Peppe sono già conteggiati. Le richieste in attesa non occupano posti. Il riepilogo Calendar viene aggiornato periodicamente.</p>
 <div className="addcrew"><h3>Aggiungi qualcuno all’equipaggio</h3><p>Il posto viene confermato subito. Per febbraio e settembre scegli anche il giorno preciso.</p><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),offer=offers.find(x=>x.id===d.get("slotId")),rule=dateRules[String(d.get("slotId"))];if(rule&&!d.get("chosenDate")){setError("Scegli la data dell’uscita.");return}const chosen=String(d.get("chosenDate")??"");const summary=`${String(d.get("name"))} · ${Number(d.get("people"))} persona/e · ${offer?.title??"Dory"}${chosen?` · ${prettyDate(chosen)}`:""}\nEmail: ${String(d.get("email"))||"non indicata"}\nNote: ${String(d.get("message"))||"nessuna"}`;if(!window.confirm(`Controlla i dati:\n\n${summary}\n\nSono corretti?`))return;void manage({action:"add",slotId:d.get("slotId"),name:d.get("name"),email:d.get("email"),people:Number(d.get("people")),message:packMessage(d.get("chosenDate"),d.get("message"))}).then(ok=>{if(ok)f.reset()})}}>
 <label>Uscita o tratta<select name="slotId" required value={adminSlot} onChange={e=>setAdminSlot(e.target.value)}>{offers.filter(x=>x.kind!=="party").map(x=><option key={x.id} value={x.id}>{x.dates} · {x.title}</option>)}</select></label>{adminRule&&<label className="date-choice">{adminRule.label}<input name="chosenDate" type="date" min={adminRule.min} max={adminRule.max} required/></label>}<label>Nome e cognome<input name="name" required minLength={2} maxLength={100}/></label><label>Email per l’invito<input name="email" type="email" placeholder="Se disponibile"/></label><label>Persone<input name="people" type="number" min="1" max="6" defaultValue="1" required/></label><label>Nota facoltativa<input name="message" maxLength={450}/></label><button className="primary">Aggiungi</button></form></div>
 {offers.filter(x=>x.kind!=="party").map(x=>{const sb=bookings.filter(b=>b.slot_id===x.id),vb=sb.filter(b=>showCancelled||b.status!=="cancelled");return <div className="adminrow" key={x.id}><strong>{x.dates} · {x.title}</strong><p>{x.confirmed} confermati · {sb.filter(b=>b.status==="pending").length} da confermare · {x.available} disponibili</p><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void manage({action:"capacity",slotId:x.id,capacity:Number(d.get("capacity")),note:d.get("note")})}}><label>Posti ospiti <input name="capacity" type="number" min="0" max="6" defaultValue={x.capacity}/></label><label>Nota <input name="note" defaultValue={x.note}/></label><button>Salva</button></form><button className="report-toggle" onClick={()=>setOpenReport(openReport===x.id?null:x.id)}>{openReport===x.id?"Chiudi report":`Report prenotazioni (${sb.filter(b=>b.status!=="cancelled").length})`}</button>{openReport===x.id&&<div className="report-group"><div className="report-head"><div><h3>Report prenotazioni</h3><p>{sb.filter(b=>b.status==="confirmed").length} confermati · {sb.filter(b=>b.status==="pending").length} in attesa</p></div><label><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/> Mostra cancellati</label></div>{vb.length===0?<p>Nessuna richiesta.</p>:vb.map(b=>{const info=unpackMessage(b.message);return <article className="booking" key={b.id}><div className="booking-title"><strong>{b.name}</strong><span className={`status ${b.status}`}>{b.status==="confirmed"?"Confermato":b.status==="pending"?"In attesa":b.status==="declined"?"Non accolto":"Cancellato"}</span></div>{info.date&&<p><strong>Data scelta: {prettyDate(info.date)}</strong></p>}<p>{b.people} {b.people===1?"persona":"persone"} · {b.added_by==="ric"?"Aggiunto da Ric":b.added_by==="peppe"?"Aggiunto da Peppe":"Richiesta dell’ospite"}</p><p>{b.email?`Email: ${b.email}`:"Email non indicata"}</p>{info.note&&<p>Note: {info.note}</p>}{b.status==="cancelled"&&<p>{b.cancellation_sent_at?"Notifica di cancellazione inviata":"Notifica di cancellazione da inviare"}</p>}{b.status==="confirmed"&&<p>{b.confirmation_sent_to===b.email&&b.confirmation_sent_at?"Conferma inviata":"Conferma email da inviare"}</p>}{b.status!=="cancelled"&&<div className="actions">{b.status!=="confirmed"&&<button onClick={()=>manage({action:"status",id:b.id,status:"confirmed"})}>Conferma</button>}{b.status==="confirmed"&&b.email&&b.confirmation_sent_to!==b.email&&<button onClick={()=>manage({action:"send-confirmation",id:b.id})}>Invia conferma</button>}<button className="danger" onClick={()=>cancelBooking(b)}>Cancella</button></div>}</article>})}</div>}</div>})}</section>:<>
 <section className="rules"><h2>Prima di salire a bordo</h2><p className="requirement"><strong>Il trick: le giornate didattiche.</strong> Per partecipare serve la tessera sportiva AICS (10 €) e un certificato medico non agonistico.</p><ul><li>Il meteo decide partenze, rotta, rada e rientro.</li><li>Per giornate e pernotti puoi lasciare un contributo libero per la cura di Dory.</li><li>Se serve un porto, la spesa si divide tra tutti, Ric e Peppe compresi.</li><li>Se il meteo ci regala il tramonto, aperitivo a bordo.</li></ul></section>
 {weeks.map((week,i)=><section key={week}><h2 className="week"><small>Settimana {i+1} di 6</small><br/>{week}</h2><div className="grid">{offers.filter(x=>x.week===week).map(x=><article className="card" key={x.id}><span className="tag">{x.dates}</span><h3>{x.title}</h3><p>{x.detail}</p><p className="muted">{x.hint}</p>{x.note&&<p className="notice">{x.note}</p>}<footer><span>{x.kind==="party"?"Adesioni aperte":x.capacity===0?"Posti ancora chiusi":`${x.available} posti disponibili`}</span><button disabled={x.capacity===0||x.available===0} onClick={()=>{setSelected(x);setNotice("");setSubmitError("");setSubmitted(false)}}>Chiedi di salire</button></footer></article>)}</div></section>)}</>}
 {login&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setLogin(false)}}><div className="modal login"><button className="close" onClick={()=>setLogin(false)}>Chiudi</button><span className="eyebrow">Solo per Ric e Peppe</span><h2>Benvenuto a bordo.</h2><form onSubmit={signIn}><label>Codice personale<input name="code" type="password" required autoFocus/></label><button className="primary" disabled={loginBusy}>{loginBusy?"Verifica…":"Entra nella gestione"}</button></form></div></div>}
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setSelected(null)}}><div className="modal"><button className="close" disabled={busy} onClick={()=>setSelected(null)}>Chiudi</button><h2>Chiedi di salire</h2><p><strong>{selected.title}</strong><br/>{selected.dates}</p>{submitted?<div className="notice"><strong>Richiesta registrata!</strong><p>Riccardo e Peppe la vedono nella gestione equipaggio.</p><button onClick={()=>setSelected(null)}>Torna alle uscite</button></div>:<form onSubmit={submit}>{dateRules[selected.id]&&<label className="date-choice">{dateRules[selected.id].label}<input name="chosenDate" type="date" min={dateRules[selected.id].min} max={dateRules[selected.id].max} required/></label>}<label>Nome e cognome<input name="name" minLength={2} maxLength={100} required/></label><label>Email<input name="email" type="email" required/></label><label>Numero di persone<input name="people" type="number" min="1" max={selected.kind==="party"?20:Math.min(6,selected.available)} defaultValue="1" required/></label><label>Note<textarea name="message" maxLength={450}/></label>{submitError&&<p className="error">{submitError}</p>}<button className="primary" disabled={busy}>{busy?"Invio…":"Invia richiesta"}</button></form>}</div></div>}</main>;
}