export type Offer = { id:string; week:string; dates:string; title:string; detail:string; hint:string; defaultCapacity:number; kind:"day"|"overnight"|"interest"|"party" };
export const offers:Offer[] = [
{id:"nov-day",week:"23–29 novembre 2026",dates:"Giovedì 26 novembre",title:"Prima uscita giornaliera",detail:"Da Ostia, con aperitivo al tramonto se le condizioni lo permettono.",hint:"Imbarco e rientro a Ostia · orari da confermare",defaultCapacity:6,kind:"day"},
{id:"nov-weekend",week:"23–29 novembre 2026",dates:"Ven 27 – dom 29 novembre",title:"Primo weekend di Dory",detail:"Argentario e Giglio oppure Ponza e Palmarola: decideremo la rotta con il meteo.",hint:"Due notti · partenza e rientro a Ostia",defaultCapacity:6,kind:"overnight"},
{id:"feb-day",week:"15–21 febbraio 2027",dates:"15–21 febbraio · scegli una giornata",title:"Uscita d’inverno",detail:"Scegli direttamente il giorno che preferisci tra il 15 e il 21 febbraio. Rientreremo nel primo pomeriggio, prima del buio.",hint:"Data selezionabile in prenotazione · Ostia",defaultCapacity:6,kind:"interest"},
{id:"feb-night",week:"15–21 febbraio 2027",dates:"15–21 febbraio · una notte, se possibile",title:"Una notte fuori",detail:"Ipotesi verso nord o sud, solo se meteo e condizioni a bordo lo consentono.",hint:"Dicci se ti va · data e scalo da confermare",defaultCapacity:6,kind:"interest"},
{id:"apr-first",week:"12–18 aprile 2027",dates:"12–15 aprile",title:"Rotta di primavera · prima tratta",detail:"Imbarco a Ostia. Rotta nord o sud e punto di sbarco saranno definiti insieme in base al meteo.",hint:"Una o due notti · cambio equipaggio da confermare",defaultCapacity:6,kind:"interest"},
{id:"apr-second",week:"12–18 aprile 2027",dates:"16–18 aprile",title:"Rotta di primavera · seconda tratta",detail:"Imbarco intermedio in uno scalo raggiungibile da Roma e rientro a Ostia domenica.",hint:"Circa due notti · luogo e orario da confermare",defaultCapacity:6,kind:"interest"},
{id:"jun-first",week:"7–13 giugno 2027",dates:"7–10 giugno",title:"Rotta di giugno · prima tratta",detail:"Partenza ipotizzata da Ostia. Rotta nord o sud da scegliere con il meteo.",hint:"Cambio equipaggio e scalo da confermare",defaultCapacity:6,kind:"interest"},
{id:"jun-second",week:"7–13 giugno 2027",dates:"11–13 giugno",title:"Rotta di giugno · seconda tratta",detail:"Imbarco intermedio in uno scalo pratico e rientro a Ostia domenica.",hint:"Imbarco e orari da confermare",defaultCapacity:6,kind:"interest"},
{id:"jul-family",week:"26 luglio – 1 agosto 2027",dates:"26 luglio – 1 agosto · giorno da definire",title:"Con le famiglie verso il Circeo",detail:"Settimana riservata alle famiglie. Valuteremo gli eventuali posti ospiti per una tratta con sbarco e rientro autonomo verso Roma.",hint:"Posti chiusi finché non contiamo entrambe le famiglie",defaultCapacity:0,kind:"interest"},
{id:"sep-day",week:"20–26 settembre 2027",dates:"20–23 settembre · scegli una giornata",title:"Uscite di fine stagione",detail:"Scegli direttamente una giornata tra il 20 e il 23 settembre. Ogni occasione sarà buona per festeggiare.",hint:"Data selezionabile in prenotazione · Ostia",defaultCapacity:6,kind:"interest"},
{id:"sep-weekend",week:"20–26 settembre 2027",dates:"24–26 settembre · weekend",title:"Ultimo weekend",detail:"Possibile notte a bordo da giovedì e partenza venerdì all’alba. Rientro domenica.",hint:"Rotta, notte iniziale e orari da confermare",defaultCapacity:6,kind:"interest"},
{id:"sep-party",week:"20–26 settembre 2027",dates:"Domenica 26, dopo il rientro",title:"Festa finale in porto",detail:"Segnala che vuoi esserci: comunicheremo ora e dettagli quando sarà confermato il rientro.",hint:"Adesione alla festa · non è un posto in barca",defaultCapacity:999,kind:"party"},
];
export const weeks=[...new Set(offers.map(o=>o.week))];
