export type Offer = { id:string; week:string; dates:string; title:string; detail:string; hint:string; defaultCapacity:number; kind:"day"|"overnight"|"interest"|"party" };
export const offers:Offer[] = [
  {id:"nov-day",week:"23–29 novembre 2026",dates:"Giovedì 26 novembre",title:"Prima uscita giornaliera",detail:"Da Ostia, con aperitivo al tramonto se le condizioni lo permettono.",hint:"Imbarco e rientro a Ostia · orari da confermare",defaultCapacity:6,kind:"day"},
  {id:"nov-weekend",week:"23–29 novembre 2026",dates:"Ven 27 – dom 29 novembre",title:"Primo weekend di Dory",detail:"Argentario e Giglio oppure Ponza e Palmarola: decideremo la rotta con il meteo.",hint:"Due notti · partenza e rientro a Ostia",defaultCapacity:6,kind:"overnight"},
  {id:"feb-day",week:"15–21 febbraio 2027",dates:"Una giornata nella settimana",title:"Uscita d’inverno",detail:"Indica nelle note i giorni che preferisci. Rientreremo nel primo pomeriggio, prima del buio.",hint:"Giorno da concordare · Ostia",defaultCapacity:6,kind:"interest"},
  {id:"feb-night",week:"15–21 febbraio 2027",dates:"Una notte, se possibile",title:"Una notte fuori",detail:"Ipotesi verso nord o sud, solo se meteo e condizioni a bordo lo consentono.",hint:"Dicci se ti va · data e scalo da confermare",defaultCapacity:6,kind:"interest"},
  {id:"apr-first",week:"12–18 aprile 2027",dates:"Prima parte · indicativamente mer–ven",title:"Rotta di primavera · prima tratta",detail:"Imbarco a Ostia. Rotta nord o sud e punto di sbarco saranno definiti insieme in base al meteo.",hint:"Una o due notti · cambio equipaggio da confermare",defaultCapacity:6,kind:"interest"},
  {id:"apr-second",week:"12–18 aprile 2027",dates:"Seconda parte · indicativamente ven–dom",title:"Rotta di primavera · seconda tratta",detail:"Imbarco intermedio in uno scalo raggiungibile da Roma e rientro a Ostia domenica.",hint:"Circa due notti · luogo e orario da confermare",defaultCapacity:6,kind:"interest"},
  {id:"jun-first",week:"7–13 giugno 2027",dates:"Prima parte · indicativamente mar–ven",title:"Rotta di giugno · prima tratta",detail:"Partenza ipotizzata da Ostia martedì. Rotta nord o sud da scegliere con il meteo.",hint:"Cambio equipaggio e scalo da confermare",defaultCapacity:6,kind:"interest"},
  {id:"jun-second",week:"7–13 giugno 2027",dates:"Seconda parte · indicativamente ven–dom",title:"Rotta di giugno · seconda tratta",detail:"Imbarco intermedio in uno scalo pratico e rientro a Ostia domenica.",hint:"Imbarco e orari da confermare",defaultCapacity:6,kind:"interest"},
  {id:"jul-family",week:"26 luglio – 1 agosto 2027",dates:"Giorno da definire",title:"Con le famiglie verso il Circeo",detail:"Settimana riservata alle famiglie. Valuteremo gli eventuali posti ospiti per una tratta con sbarco e rientro autonomo verso Roma.",hint:"Posti chiusi finché non contiamo entrambe le famiglie",defaultCapacity:0,kind:"interest"},
  {id:"sep-day",week:"20–26 settembre 2027",dates:"Giornate da definire",title:"Uscite di fine stagione",detail:"Dicci nelle note quali giorni preferisci. Ogni occasione sarà buona per festeggiare.",hint:"Dicci quando ci sei · Ostia",defaultCapacity:6,kind:"interest"},
  {id:"sep-weekend",week:"20–26 settembre 2027",dates:"Ven 24 – dom 26 settembre",title:"Ultimo weekend",detail:"Possibile notte a bordo da giovedì e partenza venerdì all’alba. Rientro domenica.",hint:"Rotta, notte iniziale e orari da confermare",defaultCapacity:6,kind:"interest"},
  {id:"sep-party",week:"20–26 settembre 2027",dates:"Domenica 26, dopo il rientro",title:"Festa finale in porto",detail:"Segnala che vuoi esserci: comunicheremo ora e dettagli quando sarà confermato il rientro.",hint:"Adesione alla festa · non è un posto in barca",defaultCapacity:999,kind:"party"},
];
export const weeks=[...new Set(offers.map(o=>o.week))];
